### PR TITLE
m1721: correct vm.dirty_* to decrease RAM usage

### PR DESCRIPTION
**Pull request by urain39**

### CODE REVIEW

**Comment by tdrkDev** [comment]
How does it cause on EMMC performace? These values were set only for emmc tuning.

**Comment by tdrkDev** [comment]
Also how much does it decreases RAM usage? I am about to merge your change, but please answer my questions before

**Comment by urain39** [comment]
> Also how much does it decreases RAM usage? I am about to merge your change, but please answer my questions before

I need some time to test. I'll get back to you later.

**Comment by urain39** [comment]
Tested on AndroBench with /data (f2fs, bfq)

dirty_ratio=30, dirty_background_ratio=15 (After)
```
SEQ RD: 261.52 MB/s
SEQ WR: 64.69 MB/s
RND RD: 9965.78 IOPS
RND WR: 3922.63 IOPS
```

dirty_ratio=90, dirty_background_ratio=50 (Before)
```
SEQ RD: 281.77 MB/s
SEQ WR: 77.69 MB/s
RND RD: 9928.34 IOPS
RND WR: 3634.61 IOPS
```

And it decreases RAM usage about 512MB and more.

**Comment by tdrkDev** [comment]
Merged manually, marked as closed.
https://github.com/meizucustoms/android_device_meizu_m1721/commit/1d0c1162bb30e9df6b921a0d3f24f8876586b081
https://github.com/meizucustoms/android_device_meizu_m1721/commit/ecdc6d6c488cba0ffb6d1ee1a335194bed1b7284

**Pull request closed without merging**
